In [1]:
import numpy as np
import pandas as pd
import pickle

df = pd.read_csv('./BH_processed.csv')
df_list = []
for k in range(10):
    r = []
    ligand = []
    add = []
    base = []
    y = []
    split_set_num = k + 1
    with open('train_test_idxs.pickle', 'rb') as handle:
        idx_dict = pickle.load(handle)

        train_index = idx_dict['train_idx'][split_set_num]
        test_index = idx_dict['test_idx'][split_set_num]
        #valid_index = train_index[int(args.valid_size*len(train_index)):]
        #train_index = train_index[0:int(args.valid_size*len(train_index))]
        order_index = np.concatenate((train_index, test_index), axis=0)
        print(order_index)
        for i in order_index:
            y.append(df['yield'].values[i])
            r.append(df['reactants'].values[i].split('.')[0])
            ligand.append(df['reagents'].values[i].split('.')[0])

            additive = df['reagents'].values[i].split('.')[2]
            #Chem.Kekulize(add)
            #Chem.MolToSmiles(m,kekuleSmiles=True)
            add.append(additive)
            base.append(df['reagents'].values[i].split('.')[1])
                    
    
        dfi = pd.DataFrame({'Ligand':ligand, 'Additive':add, 'Base':base, 'Aryl halide':r, 'Output':y})
        df_list.append(dfi)

[2887   98 1446 ... 1151 3251  601]
[1429 1278  765 ... 1523 1724 2954]
[2046 1869 1906 ... 3311  527 3313]
[3710 3674 1230 ... 2512 2340 1942]
[ 252  189 3288 ... 3021 1279 2980]
[3875  913 3182 ... 1044 2182  158]
[2292  255 3764 ... 2338 1790 2079]
[1160 1244 3548 ...  785 2779 2286]
[2703 2322 3035 ...  616  777 2339]
[2404 2241  636 ... 3563 3636 2566]


In [9]:
import numpy as np
import pandas as pd
import pickle

df = pd.read_csv('BH_processed.csv')
df_list = []

r = []
ligand = []
add = []
base = []
y = []

for i in range(df.shape[0]):
    y.append(df['yield'].values[i])
    r.append(df['reactants'].values[i].split('.')[0])
    ligand.append(df['reagents'].values[i].split('.')[0])

    additive = df['reagents'].values[i].split('.')[2]
    add.append(additive)
    base.append(df['reagents'].values[i].split('.')[1])
                    
    
dfi = pd.DataFrame({'Ligand':ligand, 'Additive':add, 'Base':base, 'Aryl halide':r, 'Output':y})
df_list.append(dfi)

In [10]:
dfi.to_csv('data1_new.csv', index=False)

In [4]:
df_list[0].head()

Ligand         Additive  \
0  CC(C)C1=CC(C(C)C)=CC(C(C)C)=C1C2=C(P(C3CCCCC3)...  o1nccc1c2ccccc2   
1  CC(C)C1=CC(C(C)C)=CC(C(C)C)=C1C2=C(P(C3CCCCC3)...  o1nccc1c2ccccc2   
2  CC(C)C1=CC(C(C)C)=CC(C(C)C)=C1C2=C(P(C3CCCCC3)...  o1nccc1c2ccccc2   
3  CC(C)C1=CC(C(C)C)=CC(C(C)C)=C1C2=C(P(C3CCCCC3)...  o1nccc1c2ccccc2   
4  CC(C)C1=CC(C(C)C)=CC(C(C)C)=C1C2=C(P(C3CCCCC3)...  o1nccc1c2ccccc2   

                                        Base           Aryl halide     Output  
0  CN(C)P(N(C)C)(N(C)C)=NP(N(C)C)(N(C)C)=NCC  FC(F)(F)c1ccc(Cl)cc1  10.657812  
1  CN(C)P(N(C)C)(N(C)C)=NP(N(C)C)(N(C)C)=NCC  FC(F)(F)c1ccc(Br)cc1  14.747896  
2  CN(C)P(N(C)C)(N(C)C)=NP(N(C)C)(N(C)C)=NCC   FC(F)(F)c1ccc(I)cc1  18.278686  
3  CN(C)P(N(C)C)(N(C)C)=NP(N(C)C)(N(C)C)=NCC        COc1ccc(Cl)cc1   2.475058  
4  CN(C)P(N(C)C)(N(C)C)=NP(N(C)C)(N(C)C)=NCC        COc1ccc(Br)cc1   6.119058

In [3]:
import pandas as pd
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows

# Sample dataframes
#df1 = df
#df2 = df

# Create a Workbook object
wb = Workbook()

# Convert DataFrame to Excel sheet
def dataframe_to_sheet(df_i, sheet):
    for r in dataframe_to_rows(df_i, index=False, header=True):
        sheet.append(r)

# Create first sheet from first dataframe
sheet1 = wb.active
sheet1.title = "FullCV_01"
dataframe_to_sheet(df_list[0], sheet1)

sheet2 = wb.create_sheet(title="FullCV_02")
dataframe_to_sheet(df_list[1], sheet2)

sheet3 = wb.create_sheet(title="FullCV_03")
dataframe_to_sheet(df_list[2], sheet3)

sheet4 = wb.create_sheet(title="FullCV_04")
dataframe_to_sheet(df_list[3], sheet4)

sheet5 = wb.create_sheet(title="FullCV_05")
dataframe_to_sheet(df_list[4], sheet5)

sheet6 = wb.create_sheet(title="FullCV_06")
dataframe_to_sheet(df_list[5], sheet6)

sheet7 = wb.create_sheet(title="FullCV_07")
dataframe_to_sheet(df_list[6], sheet7)

sheet8 = wb.create_sheet(title="FullCV_08")
dataframe_to_sheet(df_list[7], sheet8)

sheet9 = wb.create_sheet(title="FullCV_09")
dataframe_to_sheet(df_list[8], sheet9)

sheet10 = wb.create_sheet(title="FullCV_10")
dataframe_to_sheet(df_list[9], sheet10)

wb.save("new.xlsx")
print('done')


done


In [11]:
smi = 'CC1=CC(C)=NO1'
Chem.MolToSmiles(Chem.MolFromSmiles(smi))

'Cc1cc(C)on1'

In [12]:
smi = 'Cc1onc(C)c1'
Chem.MolToSmiles(Chem.MolFromSmiles(smi))

'Cc1cc(C)on1'